### ISSUE TITLE
Cannot create a SLURM cluster using dask-labextension

### ISSUE THREAD

**Issue by cbuton** [dask/dask-labextension#68]
Hello, 

My name is Clément Buton, I am a Post-doc working at [IPNL](https://www.ipnl.in2p3.fr/?lang=en) on the[ Euclid European space telescope](https://www.euclid-ec.org).

I am currently trying to use dask-labextension with a SLURM cluster on my laboratory grid infrastructure. So far, I have no problem using dask-labextension together with the local cluster configuration or opening a SLURM cluster client "by hand":

```
from dask.distributed import Client
from dask_jobqueue import SLURMCluster
cluster = SLURMCluster(cores=16, 
                                          project="euclid_nisp",
                                          local_directory='$TMPDIR',
                                          walltime='01:00:00',
                                          memory="50GB", 
                                          queue="normal")
cluster.scale(10)
client = Client(cluster, processes=False)
client
```

My problem starts when I try to configure the dask-labextension (labextension.yaml) with the SLURMCluster as follows:

```
labextension:
  factory:
    module: 'dask_jobqueue'
    class: 'SLURMCluster'
    args: []
    kwargs: {'cores': 16,
             'processes': 1,
             'memory': '50GB',
             'queue': 'normal',
             'walltime': '02:00:00',
             'local_directory': '$TMPDIR'}
  default:
    workers: null
    adapt: null
      # minimum: 0
      # maximum: 10
  initial: []
```

I get the following error message when I try to create a new cluster (i.e. click on the +new button): "cannot get address of non-running Server" (cf a copy of my screen [jupyterlab-dask-slurm.pdf](https://github.com/dask/dask-labextension/files/3358676/jupyterlab-dask-slurm.pdf)) which seems to be related to dask.distributed.

I add bellow the versions of the libraries and extensions I am currently using:

```
(py37) ✘-1 ~/dask-slurm
11:09 $ jupyter serverextension list
config dir: /home/euclid/cbuton/.miniconda/envs/py37/etc/jupyter
    dask_labextension  enabled
    - Validating...
      dask_labextension 0.4.0a1 OK
    jupyter_server_proxy  enabled
    - Validating...
      jupyter_server_proxy  OK
    jupyterlab  enabled
    - Validating...
      jupyterlab 1.0.1 OK
    jupyterlab_slurm  enabled
    - Validating...
      jupyterlab_slurm 0.1.1 OK
    nbserverproxy  enabled
    - Validating...
      nbserverproxy  OK

(py37) ✔ ~/dask-slurm
11:10 $ conda list
jupyterlab 1.0.1
jupyterlab-server 1.0.0
dask 2.0.0
dask-core 2.0.0
dask-jobqueue 0.5.0
dask-labextension 0.4.0a1
```

Any help would be deeply appreciated.
Thanks in advance, and thanks again on the really nice work you guys are doing,

Sincerely,
Clément

**Comment by TomAugspurger** [comment]
dask-jobqueue 0.6.0 was released today with compatibility for dask 2.x. Can you try with that?

**Comment by cbuton** [comment]
I updated dask (2.1.0), dask-jobqueue (0.6.0) and dask-labextension (1.0.0), but unfortunately I still have the same error message.

**Comment by TomAugspurger** [comment]
Actually, this may be a symptom of https://github.com/dask/dask-jobqueue/issues/288, which wasn't fixed in 0.6.0.

**Comment by cbuton** [comment]
Ok. Then I will stay tune and try it again as soon as [dask/dask-jobqueue#288](https://github.com/dask/dask-jobqueue/issues/288) is solved.

**Comment by guillaumeeb** [comment]
This may also come from https://github.com/dask/dask-jobqueue/issues/273. I've still not been able to play with dask-labextension and dask-jobqueue a lot. I'm only launching clusters "by hand" currently. I hope to be able to play around with all this during the summer...

also cc @andersy005 who might have played with all this.

**Comment by guillaumeeb** [comment]
By the way @cbuton, fill free to propose some Pull requests in dask-jobqueue to speed up things 🙂
